In [ ]:
from dataclasses import dataclass
from collections import deque

@dataclass
class Node:
    name : str
    offset : list
    channels : dict
    child : list
    parent : str
    first_in : bool
    
file_path = "walk60.bvh"
bvh_data = []
with open(file_path, 'r') as f:
    for line in f:
        bvh_data.append(line.split())

num_frames = 0
frame_time = 0
frames = []
joint_List = []
info_List = []
for line in bvh_data:
    this_line = line
    if(this_line[0] == "Hierarchy"): continue
    if(this_line[0] == "MOTION"): continue
    if(this_line[0] == "Frames:"):
        num_frames = int(this_line[1])
        continue
    if(this_line[0] == "Frame"):
        frame_time = float(this_line[2])
        continue
    if(this_line[0] == "{" or
       this_line[0] == "ROOT" or
       this_line[0] == "}" or
       this_line[0] == "End" or
       this_line[0] == "JOINT" or
       this_line[0] == "OFFSET" or
       this_line[0] == "CHANNELS"):
        info_List.append(this_line)
        continue
    frames.append(this_line)
    
# # 处理栈中数据
# def Process_data(stack):
#     some_data = []
#     while(stack):
#         info_pop = stack.pop()
#         if(type(info_pop) != Node and info_pop[0] == "{"):
#             break
#         elif(type(info_pop) != Node and info_pop[0] == "}"):
#             continue
#         else:
#             some_data.append(info_pop)
#     print(some_data)
#     now_node = Node(
#         name = None,
#         offset = [],
#         channels = {},
#         child = [],
#         parent = None,
#         first_in = True
#     )
#     last_node = None
#     for i in some_data:
#         # if(type(i) != Node and i[0] == "OFFSET"):
#         #     now_node.offset = [float(i[1]), float(i[2]), float(i[3])]
#         # elif(type(i) != Node  and i[0] == "CHANNELS"):
#         #     now_node.channels = {
#         #         "num_channels" : int(i[1]),
#         #         "channels" : [i[1:]]
#         #     }
#         # elif(type(i) != Node and i[0] == "JOINT"):
#         #     now_node.name = i[1]
#         # elif(type(i) == Node):
#         #     last_node = i
#         #     i += 1
#         if(type(i) == Node):
#             last_node = i
#             continue
#         if(type(i) != Node and i[0] == "OFFSET"):
#             now_node.offset = [float(i[1]), float(i[2]), float(i[3])]
#         elif(type(i) != Node and i[0] == "CHANNELS"):
#             now_node.channels = {
#                 "num_channels" : int(i[1]),
#                 "channels" : [i[1:]]}
#         elif(type(i) != Node and i[0] == "End" or i[0] == "Joint"):
#             if(i[0] == "End") : last_node.name = i[0] + i[1]
#             if(i[0] == "Joint") : last_node.name = i[1]
#             last_node.parent = now_node.name
#             now_node.child.append(last_node)
#             last_node.first_in = False
#             joint_List.append(last_node)
            
#         print(now_node)
#         print(last_node)
#     return now_node
        
    
            
len_info = len(info_List)
node_list = []
stack = deque()
# for i in range(len_info):
#     if(info_List[i][0] == "{"):
#         stack.append(info_List[i])
#         while(info_List[i][0] != "}"):
#             i += 1
#             stack.append(info_List[i])
#     elif(info_List[i][0] == "}"):
#         stack.pop()
#         print(stack.pop())
for i in range(len_info):
    if info_List[i][0] == "ROOT":
        root = Node(
             name = info_List[i][0] + info_List[i][1],
                offset = [],
                channels = {},
                child = [],
                parent = None,
                first_in = True)
        node_list.append(root)
        joint_List.append(root)
        continue
    if info_List[i][0] == "{" or info_List[i][0] == "OFFSET" or \
        info_List[i][0] == "CHANNELS" or info_List[i][0] == "End" or \
        info_List[i][0] == "JOINT":
            stack.append(info_List[i])
            continue
    if info_List[i][0] == "}":
        stack.append(info_List[i])

 
       
    
        


In [ ]:
info_List

In [ ]:
node_list

In [ ]:
class Node:
    def __init__(self, name):
        self.name = name
        self.offset = None
        self.channels = []
        self.children = []

    def __repr__(self):
        return f"Node({self.name})"


def build_skeleton(bvh_data):
    stack = []
    root = None
    current_node = None

    for line in bvh_data:
        if line[0] == 'ROOT' or line[0] == 'JOINT':
            # 创建新节点
            node = Node(line[1])
            if current_node is not None:
                # 添加为当前节点的子节点
                current_node.children.append(node)
                stack.append(current_node)
            else:
                root = node
            current_node = node
        elif line[0] == 'OFFSET':
            # 设置偏移量
            current_node.offset = tuple(map(float, line[1:]))
        elif line[0] == 'CHANNELS':
            # 设置通道信息
            current_node.channels = line[2:]  # 跳过通道数量
        elif line[0] == '}':
            # 结束当前节点的定义，返回到父节点
            if stack:
                current_node = stack.pop()
        elif line[0] == 'End' and line[1] == 'Site':
            # 处理末端节点
            end_site_node = Node('End Site')
            current_node.children.append(end_site_node)
            stack.append(current_node)
            current_node = end_site_node

    return root

# 解析示例数据
bvh_data = [['ROOT', 'Hips'], ['{'], ['OFFSET', '0.00', '0.00', '0.00'], ['CHANNELS', '6', 'Xposition', 'Yposition', 'Zposition', 'Xrotation', 'Yrotation', 'Zrotation']]
skeleton = build_skeleton(info_List)
print(skeleton.children)


In [ ]:
from dataclasses import dataclass
from collections import deque

@dataclass
class Node:
    name : str
    offset : list
    channels : dict
    child : list
    parent : str
    ID : int
    type : str
    
file_path = "walk60.bvh"
bvh_data = []
with open(file_path, 'r') as f:
    for line in f:
        bvh_data.append(line.split())

num_frames = 0
frame_time = 0
frames = []
joint_List = []
info_List = []
for line in bvh_data:
    this_line = line
    if(this_line[0] == "Hierarchy"): continue
    if(this_line[0] == "MOTION"): continue
    if(this_line[0] == "Frames:"):
        num_frames = int(this_line[1])
        continue
    if(this_line[0] == "Frame"):
        frame_time = float(this_line[2])
        continue
    if(this_line[0] == "{" or
       this_line[0] == "ROOT" or
       this_line[0] == "}" or
       this_line[0] == "End" or
       this_line[0] == "JOINT" or
       this_line[0] == "OFFSET" or
       this_line[0] == "CHANNELS"):
        info_List.append(this_line)
        continue
    frames.append(this_line)
    
offset_stack = deque()
channel_stack = deque()
node_stack = deque()
joint_List = []
node_id = 0

for info in info_List:
    if(info[0] == "ROOT"):
        node_stack.append(Node(
            name = "RootJoint",
            offset = None,
            channels = None,
            child = [],
            parent = None,
            ID = node_id,
            type = "root"
        ))
        node_id += 1
        continue
    elif info[0] == "{": continue
    elif info[0] == "OFFSET":
        offset_stack.append(list(map(float, info[1:])))
        continue
    elif info[0] == "CHANNELS":
        channel_stack.append({
            "channel_num" : int(info[1]),
            "channels" : info[2:]
        })
    elif info[0] == "JOINT":
        node_stack.append(Node(
            name = info[1],
            offset = None,
            channels = None,
            child = [],
            parent = None,
            ID = node_id,
            type = "joint"
        ))
        node_id += 1
        continue
    elif info[0] == "End":
        node_stack.append(Node(
            name = info[0] + info[1],
            offset = None,
            channels = None,
            parent = None,
            child = None,
            type = "End",
            ID = node_id
        ))
        node_id += 1
        continue
    elif info[0] == "}":
        pop_node = node_stack.pop()
        if pop_node.type == "End":
            top_node = node_stack[-1]
            pop_node.name = top_node.name + "_end"
            pop_node.parent = top_node.name
            pop_node.child = None
            offset_top = offset_stack.pop()
            pop_node.offset = offset_top
            pop_node.channels = None
            top_node.child.append(pop_node)
            joint_List.append(pop_node)
        elif pop_node.type == "joint":
            top_node = node_stack[-1]
            pop_offset = offset_stack.pop()
            pop_channels = channel_stack.pop()
            # print(pop_channels)
            pop_node.offset = pop_offset
            pop_node.channels = pop_channels
            pop_node.parent = top_node.name
            top_node.child.append(pop_node)
            joint_List.append(pop_node)
        elif pop_node.type == "root":
            pop_offset = offset_stack.pop()
            pop_channels = channel_stack.pop()
            # print(pop_channels)
            pop_node.offset = pop_offset
            pop_node.channels = pop_channels
            pop_node.parent = None
            joint_List.append(pop_node)
        continue
               
            

In [ ]:
for node in joint_List:
    if(node.name == "RootJoint"):
        print(len(node.child))

In [ ]:
from read_bvh import Bone_Tree

bone_tree = Bone_Tree('walk60.bvh')

In [ ]:
bone_tree.all_channels

In [ ]:
bone_tree.channels

In [ ]:
bone_tree.frames[0]

In [ ]:
from read_bvh import Bone_Tree

In [ ]:
import numpy as np
from scipy.spatial.transform import Rotation as R
def load_motion_data(bvh_file_path):
    """part2 辅助函数，读取bvh文件"""
    with open(bvh_file_path, 'r') as f:
        lines = f.readlines()
        for i in range(len(lines)):
            if lines[i].startswith('Frame Time'):
                break
        motion_data = []
        for line in lines[i+1:]:
            data = [float(x) for x in line.split()]
            if len(data) == 0:
                break
            motion_data.append(np.array(data).reshape(1,-1))
        motion_data = np.concatenate(motion_data, axis=0)
    return motion_data

In [ ]:
motion_data = load_motion_data(bvh_file_path= 'walk60.bvh')

In [ ]:
motion_data

In [ ]:
print(motion_data.shape)

In [ ]:
motion_data_my = Bone_Tree('walk60.bvh').frames

In [ ]:
motion_data_my

In [ ]:
from read_bvh import Bone_Tree
tree = Bone_Tree(bvh_file_path= 'walk60.bvh')

In [ ]:
tree.sorted_joint_list

In [ ]:
name_list = []
id_list = []
parent_list = []
offset_list = []
for joint in tree.sorted_joint_list:
    name_list.append(joint.name)
    id_list.append(joint.ID)
    parent_list.append(joint.parent["parent_id"])
    offset_list.append(joint.offset)
print(name_list)
print(id_list)
print(parent_list)
print(len(offset_list))
print(tree.node_count)

In [ ]:
tree.joint_List

In [ ]:
from read_bvh import Bone_Tree
tree = Bone_Tree(bvh_file_path= 'walk60.bvh')

In [ ]:
print(tree.joint_name)
print(tree.)
print(tree.joint_parent)

In [ ]:
from read_bvh import Bone_Tree
from dataclasses import dataclass
from collections import deque
import numpy as np
from scipy.spatial.transform import Rotation as R

bone_tree = Bone_Tree("walk60.bvh")

In [ ]:
joint_List = bone_tree.sorted_joint_list
joint_name = bone_tree.joint_name
joint_parent = bone_tree.joint_parent
joint_offset = bone_tree.joint_offset
motion_data = bone_tree.frames


joint_List

In [ ]:
def find_parent_rotation(Q, parent_index):
    for joint in Q:
        if joint['id'] == parent_index:
            return joint['rotation']
        
def find_parent_location(Q, parent_index):
    for joint in Q:
        if joint['id'] == parent_index:
            return joint['location']

def forward_kinematics(
        joint_list: list,
        motion_data: list,
    ) -> np.array:
        # Q4 = Q3R4 = Q2R3R4 = Q1R2R3R4 = Q0R1R2R3R4 = R0R1R2R3R4
        # DP 累推
        # return : joint_position : shape -> num_frames * num_joint * 3
        # return : joint_rotation : shape -> num_frames * num_joint * 4 (quaternion)
        joint_all_frames_info_rotation_local = []
        for frame in motion_data:
            # Q : this_frame joint_rotation -> shape : num_joint * 4
            Q = []
            # Only root joint has translation
            T0 = None
            # joint_list is sorted by ID : the sequence follow the bvh hierarchy
            for joint in joint_list:
                if joint.type == "root":
                    # root channels is 6 : first 3 is translate , second 3 is rotation
                    translate = frame[:3]
                    rotation = frame[3:6]
                    # translate_euler = R.from_euler('XYZ', translate, degrees=True)
                    T0 = np.array(translate)
                    rotation_euler = R.from_euler("XYZ", rotation, degrees=True)
                    rotation_quaternion = rotation_euler.as_quat()
                    # root's location is (0,0,0)
                    Q.append(
                        {
                            "id": 0,
                            "rotation" : rotation_quaternion,
                            "location" : np.array([0, 0, 0]),
                        }
                    )
                elif joint.type == "joint":
                    joint_index = joint.ID - 1
                    parent_index = joint.parent["parent_id"]
                    joint_rotation = frame[
                       joint.channel_index : joint.channel_index + 3
                    ]
                    #print(joint.ID)
                    #print(joint_index)
                    joint_rotation = np.array(list(map(float, joint_rotation)))
                    # parent_roation is quaternion
                    parent_rotation = find_parent_rotation(Q, parent_index)
                    #print(joint_rotation)
                    #print(type(joint_rotation))
                    #print(R.from_euler("xyz", joint_rotation, degrees=True))
                    #print(R.from_euler("xyz", joint_rotation, degrees=True).as_matrix())
                    this_joint_rotation = R.from_matrix(
                        R.from_quat(parent_rotation).as_matrix()
                        @ R.from_euler("xyz", joint_rotation, degrees=True).as_matrix()
                    ).as_quat()
                    # print(this_joint_rotation)
                    # print("--------------")
                    # parent_location is np.array -> 3 dim vec
                    parent_location = find_parent_location(Q, parent_index)
                    # joint_offset is np.array -> 3 dim vec
                    joint_offset = joint.offset
                    # ID == 1 -> need translate
                    if joint.ID == 1:
                        T0 = list(map(float, T0))
                        this_joint_location = (
                            parent_location
                            + R.from_quat(parent_rotation).apply(np.array(joint_offset))
                            + T0
                        )
                    else:
                        this_joint_location = (
                            parent_location + R.from_quat(parent_rotation).apply(np.array(joint_offset))
                        )
                    Q.append(
                        {
                            'id' : joint.ID,
                            "rotation" : this_joint_rotation,
                            "location" : this_joint_location,
                        }
                    )
                elif joint.type == "End":
                    parent_index = joint.parent["parent_id"]
                    parent_rotation = find_parent_rotation(Q, parent_index)
                    parent_location = find_parent_location(Q, parent_index)
                    this_offset = joint.offset
                    this_joint_location = parent_location + R.from_quat(parent_rotation).apply(np.array(this_offset))
                    Q.append(
                        {
                            "id" : joint.ID,
                            "rotation" : None,
                            "location" : this_joint_location
                        }
                    )
            joint_all_frames_info_rotation_local.append(Q)
        return joint_all_frames_info_rotation_local
                
                    

In [ ]:
joint_all_position = forward_kinematics(
    joint_List,
    motion_data = motion_data)
print(np.array(joint_all_position).shape)

In [ ]:
print(joint_all_position[0])

In [ ]:
from read_bvh import Bone_Tree
from dataclasses import dataclass
from collections import deque
import numpy as np
from scipy.spatial.transform import Rotation as R

bone_tree = Bone_Tree("walk60.bvh")

In [ ]:
bone_tree.all_frame_location

In [ ]:
bone_tree.all_frame_rotation

In [1]:
from read_bvh import Bone_Tree
from scipy.spatial.transform import Rotation as R
import numpy as np

In [2]:
bone_tree_A_pos = Bone_Tree("A_pose_run.bvh")
bone_tree_T_pos = Bone_Tree("walk60.bvh")

In [3]:
bone_tree_A_pos.joint_name_without_end

['RootJoint',
 'lHip',
 'lKnee',
 'lAnkle',
 'lToeJoint',
 'rHip',
 'rKnee',
 'rAnkle',
 'rToeJoint',
 'pelvis_lowerback',
 'lowerback_torso',
 'torso_head',
 'lTorso_Clavicle',
 'lShoulder',
 'lElbow',
 'lWrist',
 'rTorso_Clavicle',
 'rShoulder',
 'rElbow',
 'rWrist']

In [4]:
bone_tree_A_pos.joint_parent

[-1,
 0,
 1,
 2,
 3,
 4,
 0,
 6,
 7,
 8,
 9,
 0,
 11,
 12,
 13,
 12,
 15,
 16,
 17,
 18,
 12,
 20,
 21,
 22,
 23]

In [5]:
bone_tree_T_pos.joint_parent

[-1,
 0,
 1,
 2,
 3,
 4,
 0,
 6,
 7,
 8,
 9,
 10,
 11,
 7,
 13,
 14,
 15,
 16,
 7,
 18,
 0,
 20,
 21,
 22,
 23]

In [3]:
bone_tree_A_pos_joint_name_without_end = bone_tree_A_pos.joint_name_without_end
bone_tree_T_pos_joint_name_without_end = bone_tree_T_pos.joint_name_without_end
A_pos_frame = bone_tree_A_pos.frames
A_pos_processed_frame = bone_tree_A_pos.process_A_pos_frame(A_pos_frame = A_pos_frame,
                                                            T_pos_joint_name_without_end = bone_tree_T_pos_joint_name_without_end,
                                                            A_pos_joint_name_without_end = bone_tree_A_pos_joint_name_without_end)

In [5]:
from scipy.spatial.transform import Rotation as R
# first step -> calculate all Q-matrices
# Q-matrix is transfrom T-pos to A-pos
def calculate_Q_matrix(A_pos_frame : list, T_pos_frame : list, joint_name : list) -> list:
    Q_matrix_all_frame = [] # -> dict : {joint_name : Q_matrix} -> shape:(num_frames, num_joints)
    for A_pos_frame_this, T_pos_frame_this in zip(A_pos_frame, T_pos_frame):
        Q_matrix_this_frame = []
        print(joint_name)
        for idx, joint in enumerate(joint_name):
            A_pos_rotation = A_pos_frame_this[3 + idx * 3 : 6 + idx * 3]
            # print("A_pos_rotation : ", A_pos_rotation)
            T_pos_rotation = T_pos_frame_this[3 + idx * 3 : 6 + idx * 3]
            # print("T_pos_rotation : ", T_pos_rotation)
            A_rotation_matrix = R.from_euler("XYZ", A_pos_rotation, degrees = True)
            print("A_rotation_matrix : ", A_rotation_matrix.as_matrix())
            T_rotation_matrix = R.from_euler("XYZ", T_pos_rotation, degrees = True)
            print("T_rotation_matrix : ", T_rotation_matrix.as_matrix())
            # target_matrix * T_rotation_matrix = A_rotation_matrix
            # so -> target_matrix = A_rotation_matrix * T_rotation_matrix.inv()
            Q_this_joint = A_rotation_matrix * T_rotation_matrix.inv()
            Q_matrix_this_frame.append(
                {
                    "joint_name" : joint,
                    "Q_matrix" : Q_this_joint
                }
            )
        Q_matrix_all_frame.append(Q_matrix_this_frame)
    return Q_matrix_all_frame

In [6]:
Q_matrix = calculate_Q_matrix(A_pos_frame = A_pos_processed_frame, 
                              T_pos_frame = bone_tree_T_pos.frames,
                              joint_name = bone_tree_A_pos.joint_name_without_end)
print(Q_matrix)

['RootJoint', 'lHip', 'lKnee', 'lAnkle', 'lToeJoint', 'rHip', 'rKnee', 'rAnkle', 'rToeJoint', 'pelvis_lowerback', 'lowerback_torso', 'torso_head', 'lTorso_Clavicle', 'lShoulder', 'lElbow', 'lWrist', 'rTorso_Clavicle', 'rShoulder', 'rElbow', 'rWrist']
A_rotation_matrix :  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
T_rotation_matrix :  [[ 0.99110488  0.01380982  0.13236469]
 [-0.00928509  0.99935324 -0.03474026]
 [-0.13275884  0.03320222  0.9905921 ]]
A_rotation_matrix :  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
T_rotation_matrix :  [[ 0.9979695   0.02774396 -0.05733362]
 [-0.03840652  0.98021194 -0.19418932]
 [ 0.05081152  0.195997    0.97928717]]
A_rotation_matrix :  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
T_rotation_matrix :  [[ 0.99709511  0.07345801 -0.02013126]
 [-0.07613056  0.96930958 -0.2337586 ]
 [ 0.00234198  0.23461216  0.97208624]]
A_rotation_matrix :  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
T_rotation_matrix :  [[ 0.98548926 -0.16019507 -0.05611114]
 [ 0.1696948   0.93728974  0.30445298]
 

In [7]:
Q_matrix

[[{'joint_name': 'RootJoint',
   'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0ae9b7e40>},
  {'joint_name': 'lHip',
   'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0aea25030>},
  {'joint_name': 'lKnee',
   'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0aea25120>},
  {'joint_name': 'lAnkle',
   'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0aea25210>},
  {'joint_name': 'lToeJoint',
   'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0aea25300>},
  {'joint_name': 'rHip',
   'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0aea253f0>},
  {'joint_name': 'rKnee',
   'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0aea254e0>},
  {'joint_name': 'rAnkle',
   'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0aea255d0>},
  {'joint_name': 'rToeJoint',
   'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0aea256c0>},
  {'joint_name': 'pelvis_lowerback',
   'Q_

In [ ]:
# ok -> all_Q_has_been_calculated
Q_matrix[0][0]['Q_matrix'].as_matrix() 
print((Q_matrix[0]))


In [8]:
bone_tree_A_pos.sorted_joint_list

[Node(name='RootJoint', offset=[0.0, 0.0, 0.0], channels={'channel_num': 6, 'channels': ['Xposition', 'Yposition', 'Zposition', 'Xrotation', 'Yrotation', 'Zrotation']}, child=[Node(name='lHip', offset=[0.1, -0.051395, 0.0], channels={'channel_num': 3, 'channels': ['Xrotation', 'Yrotation', 'Zrotation']}, child=[Node(name='lKnee', offset=[0.0, -0.41, 0.0], channels={'channel_num': 3, 'channels': ['Xrotation', 'Yrotation', 'Zrotation']}, child=[Node(name='lAnkle', offset=[0.0, -0.39, 0.0], channels={'channel_num': 3, 'channels': ['Xrotation', 'Yrotation', 'Zrotation']}, child=[Node(name='lToeJoint', offset=[0.0, -0.05, 0.13], channels={'channel_num': 3, 'channels': ['Xrotation', 'Yrotation', 'Zrotation']}, child=[Node(name='lToeJoint_end', offset=[0.01, 0.002, 0.06], channels=None, child=None, parent={'parent_name': 'lToeJoint', 'parent_id': 4}, ID=5, channel_index=None, type='End')], parent={'parent_name': 'lAnkle', 'parent_id': 3}, ID=4, channel_index=15, type='joint')], parent={'paren

In [17]:
Q_matrix[1]

[{'joint_name': 'RootJoint',
  'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0aea37300>},
 {'joint_name': 'lHip',
  'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0aea373f0>},
 {'joint_name': 'lKnee',
  'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0aea374e0>},
 {'joint_name': 'lAnkle',
  'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0aea375d0>},
 {'joint_name': 'lToeJoint',
  'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0aea376c0>},
 {'joint_name': 'rHip',
  'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0aea377b0>},
 {'joint_name': 'rKnee',
  'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0aea378a0>},
 {'joint_name': 'rAnkle',
  'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0aea37990>},
 {'joint_name': 'rToeJoint',
  'Q_matrix': <scipy.spatial.transform._rotation.Rotation at 0x1f0aea37a80>},
 {'joint_name': 'pelvis_lowerback',
  'Q_matrix': <scipy.spat

In [46]:
def find_node(node_list : list, joint_name : str):
    for node in node_list:
        if(node.name == joint_name):
            return node

def find_Q(Q_matrix : list , joint_name : str):
    for Q in Q_matrix:
        if(Q['joint_name'] == joint_name):
            return Q['Q_matrix']

# for root node -> Rotation_in_A_pos = Rotation_in_T_pos * Q(from_T_pos_to_A_pos)^T
# for none root node -> Rotation_in_A_pos = Q(parent_from_T_pos_to_A_pos) * Rotation_in_T_pos * Q(this_joint_from_T_pos_to_A_pos)

def motion_retarget(Q_matrix : list, T_pos_all_frames : list, node_list_in_A_pos : list, node_list_in_T_pos : list) -> list:
    # input : rotation_in_A_pos_all_frames,
    #         tranformation_matrix_from_T_pos_to_A_pos
    #         rotation_in_T_pos_all_frames
    # output : retargeting_motion_from_A_pos_to_T_pos_all_frames
    all_frame_new_rotation_in_T_pos = []
    for idx, T_pos_frame in enumerate(T_pos_all_frames):
        this_T_pos_frame = T_pos_frame
        # print(this_T_pos_frame)
        # print(idx)
        # print(Q_matrix)
        this_frame_all_Q_matrix = Q_matrix[int(idx)]
        # print(this_frame_all_Q_matrix)
        this_frame_new_rotation_in_T_pos = []
        for idx_joint, one_Q_matrix in enumerate(this_frame_all_Q_matrix):
            joint_name = one_Q_matrix['joint_name']
            Q_matrix_this_joint = one_Q_matrix['Q_matrix']
            this_joint_rotation_in_T_pos = this_T_pos_frame[3 + 3 * idx_joint : 6 + 3 * idx_joint]
            joint_node_in_A_pos = find_node(node_list_in_A_pos, joint_name)
            joint_parent_name = joint_node_in_A_pos.parent['parent_name'] 
            parent_Q_matrix = find_Q(this_frame_all_Q_matrix, joint_parent_name)
            if(joint_node_in_A_pos.type == 'root'):
                # this is a root node
                # print("this_joint_rotation_in_T_pos: ", this_joint_rotation_in_T_pos)
                # print("Q_matrix_this_joint: ", Q_matrix_this_joint.as_matrix())
                # add T_pos translation to the new_frame_info
                this_frame_new_rotation_in_T_pos.append(this_T_pos_frame[0 : 3])
                B_rotation = R.from_euler("XYZ", this_joint_rotation_in_T_pos, degrees = True).as_matrix() * Q_matrix_this_joint.as_matrix().transpose()
                this_frame_new_rotation_in_T_pos.append(R.from_matrix(B_rotation).as_euler("XYZ", degrees = True).tolist())
                continue
            else:
                B_rotation = parent_Q_matrix.as_matrix() * R.from_euler("XYZ", this_joint_rotation_in_T_pos, degrees = True).as_matrix() * Q_matrix_this_joint.as_matrix().transpose()
                this_frame_new_rotation_in_T_pos.append(R.from_matrix(B_rotation).as_euler("XYZ", degrees = True).tolist())
        all_frame_new_rotation_in_T_pos.append(np.array(this_frame_new_rotation_in_T_pos).reshape(-1, len(this_T_pos_frame)).tolist()) 
    return np.array(all_frame_new_rotation_in_T_pos).squeeze().tolist()
                     

In [47]:
new_frame = motion_retarget(
    Q_matrix,
    T_pos_all_frames = bone_tree_T_pos.frames,
    node_list_in_A_pos = bone_tree_A_pos.sorted_joint_list,
    node_list_in_T_pos = bone_tree_T_pos.sorted_joint_list
)

In [49]:
new_frame

[['-0.001735',
  '0.855388',
  '0.315499',
  '-0.0030222368960485637',
  '-0.003022077483365596',
  '-0.0030222368960485637',
  '-0.07605333097995616',
  '-0.022880207585682127',
  '0.0007939094116803754',
  '-0.6388062709235889',
  '0.0005628604078592455',
  '0.010990379156768752',
  '-1.3676137706105054',
  '-0.0012668338209258381',
  '0.12604467988378903',
  '0.35086501454792235',
  '-2.0106501894033058e-05',
  '-0.007077061761709183',
  '-0.002965208697814157',
  '-0.0021397542717842125',
  '0.0002707813767908403',
  '-0.002612572908121522',
  '0.011805463214036499',
  '0.0013692192452455561',
  '-0.0026604237204500922',
  '0.00032694771292310695',
  '-0.22885465840472524',
  '0.5403410005096183',
  '-0.21195842973781523',
  '153.19706083764325',
  '-0.0008816769167888896',
  '-1.4651407179981886',
  '0.003965022964702761',
  '5.3208809094954314e-05',
  '0.04898652067472199',
  '-0.031796291739304795',
  '-0.000582445769660278',
  '-0.029386675248667022',
  '-0.6684758032526058',
 