In [1]:
from scipy.spatial.transform import Rotation as R
import numpy as np

In [2]:
r = R.from_quat([0, 0, np.sin(np.pi / 4), np.cos(np.pi / 4)])
r

In [4]:
r.as_matrix()

array([[ 0., -1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.]])

In [5]:
r.as_rotvec()

array([0.        , 0.        , 1.57079633])

In [7]:
r.as_euler('zyx', degrees=True)

array([90.,  0.,  0.])

In [8]:
r.as_euler('xyz', degrees= True)

array([ 0.,  0., 90.])

In [9]:
r2 = R.from_matrix(np.array([[0, -1, 0], [1, 0, 0], [0, 0, 1]]))

In [11]:
r2.as_euler('xyz', degrees=True)

array([ 0.,  0., 90.])

In [12]:
r2.as_quat()

array([0.        , 0.        , 0.70710678, 0.70710678])

In [14]:
r3 = R.from_euler("xyz", [2.008551 ,7.606260,  -0.798294], degrees=True)

In [15]:
r3.as_quat()

array([ 0.01794999,  0.06619478, -0.00811248,  0.99761227])

In [16]:
v = [1, 2, 3]
r.apply(v)

array([-2.,  1.,  3.])

In [17]:
r4 = R.from_euler("xyz",[11.216058, -3.286777, -1.592436], degrees= True)

In [22]:
r3 = R.from_euler("xyz", [2.008551 ,7.606260,  -0.798294], degrees=True).as_quat()
r4 = R.from_euler("xyz",[11.216058, -3.286777, -1.592436], degrees= True).as_quat()

In [26]:
r3 = R.from_euler("xyz", [2.008551 ,7.606260,  -0.798294], degrees=True).as_quat()
r4 = R.from_euler("xyz",[11.216058, -3.286777, -1.592436], degrees= True).as_quat()
roation3 = R.from_quat(r3)
rotation4 = R.from_quat(r4)
rotation34 = R.from_matrix(roation3.as_matrix() @ rotation4.as_matrix()).as_quat()
rotation34

array([ 0.11392745,  0.03543115, -0.02604106,  0.99251551])

In [27]:
rotation43 = R.from_matrix(rotation4.as_matrix() @ roation3.as_matrix()).as_quat()
rotation43


array([ 0.11587167,  0.03661377, -0.01208945,  0.99251551])