In [1]:
# from task1_forward_kinematics import *
from scipy.spatial.transform import Rotation as R
from Lab2_IK_answers import *
from task2_inverse_kinematics import *
from viewer import *

In [2]:
viewer = SimpleViewer()
target_pos = np.array([0.5, 0.75, 0.5])

In [3]:
viewer.create_marker(target_pos, [1, 0, 0, 1])
joint_name, joint_parent, joint_initial_position = viewer.get_meta_data()
meta_data = MetaData(joint_name, joint_parent, joint_initial_position, 'lToeJoint_end', 'lWrist_end')
joint_position = viewer.get_joint_positions()
joint_orientation = viewer.get_joint_orientations()

In [5]:
joint_name

['RootJoint',
 'pelvis_lowerback',
 'lowerback_torso',
 'rHip',
 'lHip',
 'rKnee',
 'lKnee',
 'rAnkle',
 'lAnkle',
 'rToeJoint',
 'lToeJoint',
 'torso_head',
 'rTorso_Clavicle',
 'lTorso_Clavicle',
 'rShoulder',
 'lShoulder',
 'rElbow',
 'lElbow',
 'rWrist',
 'lWrist',
 'torso_head_end',
 'lWrist_end',
 'rWrist_end',
 'lToeJoint_end',
 'rToeJoint_end']

In [6]:
joint_parent

[-1,
 0,
 1,
 0,
 0,
 3,
 4,
 5,
 6,
 7,
 8,
 2,
 2,
 2,
 12,
 13,
 14,
 15,
 16,
 17,
 11,
 19,
 18,
 10,
 9]

In [7]:
joint_initial_position

array([[-1.18591476e-19,  9.31395352e-01,  0.00000000e+00],
       [ 0.00000000e+00,  1.02499998e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.12500000e+00,  0.00000000e+00],
       [-1.00000001e-01,  8.79999995e-01,  0.00000000e+00],
       [ 1.00000001e-01,  8.79999995e-01,  0.00000000e+00],
       [-1.00000001e-01,  4.69999999e-01,  0.00000000e+00],
       [ 1.00000001e-01,  4.69999999e-01,  0.00000000e+00],
       [-1.00000001e-01,  7.99999833e-02,  0.00000000e+00],
       [ 1.00000001e-01,  7.99999833e-02,  0.00000000e+00],
       [-1.00000001e-01,  2.99999714e-02,  1.29999995e-01],
       [ 1.00000001e-01,  2.99999714e-02,  1.29999995e-01],
       [ 0.00000000e+00,  1.40734994e+00,  0.00000000e+00],
       [-1.00000005e-03,  1.28250003e+00,  0.00000000e+00],
       [ 1.00000005e-03,  1.28250003e+00,  0.00000000e+00],
       [-1.18647002e-01,  1.28250003e+00,  0.00000000e+00],
       [ 1.18647002e-01,  1.28250003e+00,  0.00000000e+00],
       [-3.63647014e-01,  1.28250003e+00

In [8]:
joint_position

array([[-1.18591476e-19,  9.31395352e-01,  0.00000000e+00],
       [ 0.00000000e+00,  1.02499998e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.12500000e+00,  0.00000000e+00],
       [-1.00000001e-01,  8.79999995e-01,  0.00000000e+00],
       [ 1.00000001e-01,  8.79999995e-01,  0.00000000e+00],
       [-1.00000001e-01,  4.69999999e-01,  0.00000000e+00],
       [ 1.00000001e-01,  4.69999999e-01,  0.00000000e+00],
       [-1.00000001e-01,  7.99999833e-02,  0.00000000e+00],
       [ 1.00000001e-01,  7.99999833e-02,  0.00000000e+00],
       [-1.00000001e-01,  2.99999714e-02,  1.29999995e-01],
       [ 1.00000001e-01,  2.99999714e-02,  1.29999995e-01],
       [ 0.00000000e+00,  1.40734994e+00,  0.00000000e+00],
       [-1.00000005e-03,  1.28250003e+00,  0.00000000e+00],
       [ 1.00000005e-03,  1.28250003e+00,  0.00000000e+00],
       [-1.18647002e-01,  1.28250003e+00,  0.00000000e+00],
       [ 1.18647002e-01,  1.28250003e+00,  0.00000000e+00],
       [-3.63647014e-01,  1.28250003e+00

In [9]:
joint_orientation

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

: 